name: Setup strava webhook

on: workflow_dispatch

jobs:
  setup-strava-webhook:
    runs-on: ubuntu-latest

    steps:
      - run: |
          curl -X POST https://www.strava.com/api/v3/push_subscriptions \
            -F client_id=${STRAVA_CLIENT_ID} \
            -F client_secret=${STRAVA_CLIENT_SECRET} \
            -F verify_token=${STRAVA_VERIFY_TOKEN} \
            -F callback_url=https://100cims.vercel.app/api/strava/webhook
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_VERIFY_TOKEN: ${{ secrets.STRAVA_VERIFY_TOKEN }}
